version: "3"

services:
  todo-app:
    build: ./
    ports:
      - 5000:5000
    environment:
      - SERVICE_NAME=mongo
      - SERVICE_PORT=27017
  mongo:
    image: mongo
    ports:
      - 27017:27017
